edition = "2021"
fn_args_layout = "Tall"
hard_tabs = false
max_width = 100
merge_derives = false
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
